# Generated by Django 2.2.2 on 2019-08-14 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(default='uyFN5uIEje6lAonkIU5vagalD42dNk89XRtN5Z5DeJNPFSBP4Tl2rTwZi5gIx53K', max_length=64, unique=True)),
                ('file', models.BooleanField(default=False)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QueryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('gerrit_username', models.CharField(default='', max_length=40)),
                ('github_username', models.CharField(default='', max_length=40)),
                ('phabricator_username', models.CharField(default='', max_length=40)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Query')),
            ],
        ),
        migrations.CreateModel(
            name='QueryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='query.Query')),
            ],
        ),
    ]
