# Generated by Django 2.2.2 on 2019-06-13 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='query',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='8f4VOyXvx9TvO01Gko9ZQcasLMKzMeuEnZPJnFCrIJrE8SIOhIOQkS95BLizfEfo', max_length=64, unique=True),
        ),
    ]
