# Generated by Django 2.2.2 on 2019-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20190614_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='7Ab3BiAy0rbHzbdlOLCG5CDwuAwJL3r5K5tp27LogFYmMt5PIzYJ8z9sTSd7RgfI', max_length=64, unique=True),
        ),
    ]
