# Generated by Django 2.2.2 on 2019-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_auto_20190614_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='QAifSYg83XyN2HrC2mQdV2mhjAkRWgbu8xK3lpqfb1yNBHplh0PswXMdPi2oXant', max_length=64, unique=True),
        ),
    ]
