# Generated by Django 2.2.2 on 2019-07-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20190615_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryfilter',
            name='project',
        ),
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='rob4iEmKLosQQygj3QH102nhM2gunLHPXgf2k74kmOpPZIbp7HFzeL5KhgfTlzG7', max_length=64, unique=True),
        ),
    ]
