# Generated by Django 2.2.2 on 2019-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_auto_20190711_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='mef63bICC5QN1jqyGxM2USfMHxoTeCe7y7vg0qmf7azNqk0QE2N2WCN10fj7v4Nz', max_length=64, unique=True),
        ),
    ]
