# Generated by Django 2.2.2 on 2019-07-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_auto_20190711_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='kiNr8mA3DnA968u45DALAvgAgwrU1pt87Y2PJc8hyhbrTjOTjuCACaO1Cs18ccH9', max_length=64, unique=True),
        ),
    ]
