# Generated by Django 2.2.2 on 2019-07-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0012_auto_20190714_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='h7oX1gwaK369uHTtm3uvWLJUUDEv1oND0Ihsnavt777OVt17GXf4Hu7Lw1m2iwvK', max_length=64, unique=True),
        ),
    ]
