# Generated by Django 2.2.2 on 2019-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0013_auto_20190716_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='o8M4KqtdFJKUESSeSrYlSgAwfmt4vNrECzJoW9MSGnSrD2w8Hgboai1Z6uEwxs0e', max_length=64, unique=True),
        ),
    ]
