# Generated by Django 2.2.2 on 2019-07-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0015_auto_20190717_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='7qINcMyKIDih2KrbdZO1NnXnrNIT35MoKPXkL3T7IHuLygryvne7DmdqJ1QGpz7A', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='queryfilter',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queryfilter',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
