# Generated by Django 2.2.2 on 2019-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0016_auto_20190721_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='JkU0kPBoXulIU3wtYM5pu1i8ErxFaQpYLngmbCuhfrDKeUTMxRHsivhY1vWLFI8F', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='queryfilter',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queryfilter',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
