# Generated by Django 2.2.2 on 2019-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_auto_20190721_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='MUA2N0EREJ64BawJ4BzaUglIoyqfNqKGhkkJF7Us8m9U4iyfQdAM5rElpDa0Kgez', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='queryfilter',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queryfilter',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
