# Generated by Django 2.2.2 on 2019-07-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0018_auto_20190721_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='roKhPU5e8TugX3dQ4oJGr1dbmAgRfC4gZ4kBOdth0TVM1QzNWvF0vOL7Wl2yVyH8', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='queryuser',
            name='fullname',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
