# Generated by Django 2.2.2 on 2019-07-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0019_auto_20190721_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='JoOPReFeFj1bkQBH2FVB3QXExjDcwoHiH4x8PqrpWK10kcMbNTPaHnhrtNqTMHzl', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='queryuser',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
