# Generated by Django 2.2.2 on 2019-08-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='7vOkTPglVe5klNyBtrGS3N829hxmjIYr8zVYRfPMvBfzC9aiqJqeS1BkwrhfvYRD', max_length=64, unique=True),
        ),
    ]
