# Generated by Django 2.2.2 on 2019-06-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(default='iHlBeiKdlGPf3LYVb6aBRiGttmlaS9Eizkzt3dcLwOc0UZR0fXIjiUkJXB4cta2H', max_length=64, unique=True)),
                ('file', models.BooleanField(default=False)),
                ('csv_file', models.FileField(upload_to='uplaods/')),
            ],
        ),
        migrations.CreateModel(
            name='QueryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('gerrit_username', models.CharField(default='', max_length=40)),
                ('github_username', models.CharField(default='', max_length=40)),
                ('phabricator_username', models.CharField(default='', max_length=40)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Query')),
            ],
        ),
        migrations.CreateModel(
            name='QueryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=40)),
                ('project', models.CharField(max_length=100)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Query')),
            ],
        ),
    ]
