# Generated by Django 2.2.2 on 2019-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20190613_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='hash_code',
            field=models.CharField(default='AD4nL5HiwX7ElviJh9lWZe57BYvTEQg6UqES5ZkhA2l1jYcktaXK0wfGk5WqS8II', max_length=64, unique=True),
        ),
    ]
